services:
  quote-buddy:
    image: ghcr.io/kingscouter/citationbuddy:latest
    pull_policy: always
    container_name: quote-buddy
    volumes:
      - /home/app/quote-buddy/quote-buddy.env:/home/node/app/config.env
      - /home/app/quote-buddy/db/:/home/node/app/db/
    environment:
      - BOT_ENV_PATH=/home/node/app/config.env
    network_mode: host
    user: "1000:1000"
    restart: unless-stopped
