allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bufferutil: true
  core-js-pure: true
  cypress: false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: true
  utf-8-validate: true
  zlib-sync: true
