name: Deploy Docker Image
concurrency:
  group: deploy-docker-image
  cancel-in-progress: true
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            compose.yaml
          sparse-checkout-cone-mode: false

      - name: Deploy compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VSHE_SSH_HOST }}
          username: ${{ secrets.VSHE_SSH_USERNAME }}
          password: ${{ secrets.VSHE_SSH_PASSWORD }}
          source: "compose.yaml"
          target: "/home/app/"

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VSHE_SSH_HOST }}
          password: ${{ secrets.VSHE_SSH_PASSWORD }}
          username: ${{ secrets.VSHE_SSH_USERNAME }}
          script: |
            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f /home/app/compose.yaml up
